import { createFileRoute } from '@tanstack/react-router'
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Copy, Sparkles } from "lucide-react";

export const Route = createFileRoute("/_authenticated/tools")({ component: ToolsPage });
const copyButton = <Button size="sm" variant="outline" className="gap-1"><Copy className="h-3.5 w-3.5" />نسخ</Button>;

function ToolsPage() {
  return <AppShell><div className="mx-auto max-w-4xl space-y-6" dir="rtl"><header><p className="text-sm text-muted-foreground">مساحة التحسين</p><h1 className="text-2xl font-bold">أدوات الكتابة الذكية</h1></header><Tabs defaultValue="headline"><TabsList className="grid h-auto w-full grid-cols-3"><TabsTrigger value="headline">محسّن الـ Headline</TabsTrigger><TabsTrigger value="comment">مساعد التعليق</TabsTrigger><TabsTrigger value="summary">محسّن الملخص</TabsTrigger></TabsList><TabsContent value="headline" className="space-y-4 pt-3"><ToolInput placeholder="الصق عنوانك الحالي على LinkedIn" button="حسّن العنوان ✨" /><div className="grid gap-3">{["أساعد الفرق على تحويل الأفكار المعقدة إلى نتائج واضحة", "قائد منتجات يبني تجارب رقمية يحبها المستخدمون", "صانع أثر رقمي | من الاستراتيجية إلى التنفيذ"].map((text) => <ResultCard key={text} title={text} description="أكثر تحديداً، يوضح القيمة التي تقدمها ويترك انطباعاً مهنياً سريعاً." />)}</div></TabsContent><TabsContent value="comment" className="space-y-4 pt-3"><ToolInput placeholder="الصق المنشور الذي تريد التعليق عليه" button="اقترح تعليقاً ✨" /><div className="grid gap-3 md:grid-cols-3">{[["موافق 👍", "أتفق تماماً، وأضيف أن التركيز على بناء العادات الصغيرة هو ما يجعل التغيير مستداماً."], ["محايد 🤔", "وجهة نظر مهمة. أعتقد أن السياق وحجم الفريق يصنعان فرقاً كبيراً في تطبيق هذه الفكرة."], ["مختلف بأدب 🗣️", "أحترم هذه النظرة، لكن تجربتي تشير إلى أن البدء بالتجربة السريعة قد يكشف فرصاً لا نراها في التخطيط فقط."]].map(([title, text]) => <ResultCard key={title} title={title} description={text} />)}</div></TabsContent><TabsContent value="summary" className="space-y-4 pt-3"><ToolInput placeholder="الصق ملخصك الحالي أو اكتب نبذة مختصرة" button="حسّن الملخص ✨" /><div className="grid gap-3 md:grid-cols-2"><Card className="p-5"><p className="mb-3 text-sm font-semibold text-muted-foreground">قبل</p><p className="text-sm leading-7">محترف في مجال المنتجات الرقمية، مهتم بالتقنية والعمل مع الفرق.</p></Card><Card className="border-primary/30 bg-primary/5 p-5"><p className="mb-3 text-sm font-semibold text-primary">بعد</p><p className="text-sm leading-7">أقود تطوير منتجات رقمية تحول احتياجات المستخدمين إلى تجارب سهلة وقابلة للنمو، وأؤمن بأن أفضل الحلول تبدأ بالاستماع الجيد.</p></Card></div><Button className="gap-2"><Copy className="h-4 w-4" />نسخ النسخة المحسّنة</Button></TabsContent></Tabs></div></AppShell>;
}
function ToolInput({ placeholder, button }: { placeholder: string; button: string }) { return <Card className="space-y-4 p-5"><Textarea placeholder={placeholder} rows={5} /><Button onClick={() => { /* TODO: call improveHeadline(text) */ /* TODO: call generateComment(post) */ /* TODO: call improveSummary(text) */ }} className="gap-2"><Sparkles className="h-4 w-4" />{button}</Button></Card>; }
function ResultCard({ title, description }: { title: string; description: string }) { return <Card className="p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold">{title}</h3>{copyButton}</div><p className="mt-3 text-sm leading-7 text-muted-foreground">{description}</p></Card>; }
