/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPosts_newRouteImport } from './routes/_authenticated/posts_new'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated/posts'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLinkedinRouteImport } from './routes/_authenticated/linkedin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPostsNewRouteImport } from './routes/_authenticated/posts.new'
import { Route as ApiPublicLinkedinCallbackRouteImport } from './routes/api/public/linkedin.callback'
import { Route as ApiPublicCronPublishRouteImport } from './routes/api/public/cron.publish'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosts_newRoute = AuthenticatedPosts_newRouteImport.update({
  id: '/posts_new',
  path: '/posts_new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkedinRoute = AuthenticatedLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostsNewRoute = AuthenticatedPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedPostsRoute,
} as any)
const ApiPublicLinkedinCallbackRoute =
  ApiPublicLinkedinCallbackRouteImport.update({
    id: '/api/public/linkedin/callback',
    path: '/api/public/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPublishRoute = ApiPublicCronPublishRouteImport.update({
  id: '/api/public/cron/publish',
  path: '/api/public/cron/publish',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/linkedin': typeof AuthenticatedLinkedinRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/posts': typeof AuthenticatedPostsRouteWithChildren
  '/posts_new': typeof AuthenticatedPosts_newRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/linkedin': typeof AuthenticatedLinkedinRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/posts': typeof AuthenticatedPostsRouteWithChildren
  '/posts_new': typeof AuthenticatedPosts_newRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/linkedin': typeof AuthenticatedLinkedinRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRouteWithChildren
  '/_authenticated/posts_new': typeof AuthenticatedPosts_newRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/posts/new': typeof AuthenticatedPostsNewRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/linkedin'
    | '/onboarding'
    | '/planner'
    | '/posts'
    | '/posts_new'
    | '/settings'
    | '/tools'
    | '/posts/new'
    | '/api/public/cron/publish'
    | '/api/public/linkedin/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/linkedin'
    | '/onboarding'
    | '/planner'
    | '/posts'
    | '/posts_new'
    | '/settings'
    | '/tools'
    | '/posts/new'
    | '/api/public/cron/publish'
    | '/api/public/linkedin/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/linkedin'
    | '/_authenticated/onboarding'
    | '/_authenticated/planner'
    | '/_authenticated/posts'
    | '/_authenticated/posts_new'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/posts/new'
    | '/api/public/cron/publish'
    | '/api/public/linkedin/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronPublishRoute: typeof ApiPublicCronPublishRoute
  ApiPublicLinkedinCallbackRoute: typeof ApiPublicLinkedinCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts_new': {
      id: '/_authenticated/posts_new'
      path: '/posts_new'
      fullPath: '/posts_new'
      preLoaderRoute: typeof AuthenticatedPosts_newRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/linkedin': {
      id: '/_authenticated/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof AuthenticatedLinkedinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/new': {
      id: '/_authenticated/posts/new'
      path: '/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthenticatedPostsNewRouteImport
      parentRoute: typeof AuthenticatedPostsRoute
    }
    '/api/public/linkedin/callback': {
      id: '/api/public/linkedin/callback'
      path: '/api/public/linkedin/callback'
      fullPath: '/api/public/linkedin/callback'
      preLoaderRoute: typeof ApiPublicLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/publish': {
      id: '/api/public/cron/publish'
      path: '/api/public/cron/publish'
      fullPath: '/api/public/cron/publish'
      preLoaderRoute: typeof ApiPublicCronPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPostsRouteChildren {
  AuthenticatedPostsNewRoute: typeof AuthenticatedPostsNewRoute
}

const AuthenticatedPostsRouteChildren: AuthenticatedPostsRouteChildren = {
  AuthenticatedPostsNewRoute: AuthenticatedPostsNewRoute,
}

const AuthenticatedPostsRouteWithChildren =
  AuthenticatedPostsRoute._addFileChildren(AuthenticatedPostsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLinkedinRoute: typeof AuthenticatedLinkedinRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRouteWithChildren
  AuthenticatedPosts_newRoute: typeof AuthenticatedPosts_newRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLinkedinRoute: AuthenticatedLinkedinRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPostsRoute: AuthenticatedPostsRouteWithChildren,
  AuthenticatedPosts_newRoute: AuthenticatedPosts_newRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronPublishRoute: ApiPublicCronPublishRoute,
  ApiPublicLinkedinCallbackRoute: ApiPublicLinkedinCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
